== Загальний опис

Бекенд-сервіс надання конфігурації регламенту реєстру

*Сервіс надає наступний функціонал*

* Версіонована розробка регламенту реєстру

* Створення та редагування:
** Форм
** Бізнес процесів

* Перегляд стану:
** Модель даних

* Пакетне завантаження даних користувачів в keycloak
* Отримання переліку шаблонів звітів реєстру

[NOTE]
Всі інші необхідні операції над сутностями конфігурації регламенту реєстру повинні бути виконані з використанням _git та gerrit_ розробником регламенту реєстру

== Загальні принципи реалізації
* Кожній версії-кандидату відповідає Merge Request в Gerrit
* Кожній версії-кандидат має свою власну _git clone_ директорію
* Мастер версія регламенту має свою власну директорію _git clone_
* Файлова система контейнеру є _persistent volume_
* RestAPI для отримання інфорамції про сутності реглвменту реєстру використовую git репозиторії на файловій системі
* Для забезпечення організації одночасної роботи в рамках однієї версії-кандидату використовується Optimistic locking на рівні RestAPI
* Для сутностей _Форми_ та _Бізнес процеси_ є 1-1 відношення в розрізі сутність та файл на файловій системі
* Всі _Дата модель_ сутності знаходяться в одному файлі на файловій системі _DataModelSnapshot.json_

