spring:
  zipkin:
    enabled: false
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  jackson:
    deserialization:
      fail-on-missing-creator-properties: true
      fail-on-null-creator-properties: true

server:
  port: 7070

platform:
  security:
    enabled: false

user-import-ceph:
  http-endpoint: http://localhost:4566
  access-key: access-key
  secret-key: secret-key
  bucket: bucket

s3:
  config:
    client:
      protocol: http
      signerOverride: S3SignerType
    options:
      pathStyleAccess: true

logging:
  level:
    root: INFO
    org.zalando.logbook: TRACE
  pattern:
    #   Logging patterns inherited from Spring Boot default logging system configuration
    #   add tracing
    console: '%d{${LOG_DATEFORMAT_PATTERN}} [trace:%X{traceId}/%X{spanId}/%X{x-request-id}] ${LOG_LEVEL_PATTERN} %pid --- [%15.15t] %-40.40c{1.} : %m%n${LOG_EXCEPTION_CONVERSION_WORD}'

openshift:
  namespace: test
  job:
    name: test

keycloak:
  realm: test-realm

file-validator:
  encoding: UTF-8
  extension: csv

vault:
  key: key

gerrit:
  url: https://gerrit
  repository: registry-regulations
  repository-directory: ${java.io.tmpdir}
  user: user
  password: password
  head-branch: master

scheduled:
  repositoryRefreshCron: '0 */5 * ? * *'
  repositoryRefreshTimezone: UTC
  cleanRepositoriesCron: '0 */5 * ? * *'
  cleanRepositoriesTimezone: UTC