== Версії регламенту

Модуль для організації роботи з версіями регламенту.

.Виділяються наступні версії регламенту:
- Майстер-версія регламенту - це поточна версія регламенту, що розгорнута на платформі
- Версія-кандидат регламенту - це версія яка є кандидатом на те, щоб стати майстер версією регламенту

.Надає наступний функціонал:
- Отримання інформації про майстер-версію регламенту
- Отримання списку всіх версій-кандидатів регламенту
- Отримання інформації про версію-кандидат регламенту
- Створення нової версії-кандидата
- Перевірка наявності змін у версії-кандидаті що конфліктують з майстер-версією
- Застосування версії-кандидату до майстер-версії
- Відхилення версії-кандидату

=== Отримання інформації про майстер-версію регламенту

Повертає інформацію про останню застосовану версію-кандидата. Якщо жодної версії-кандидата не було застосовано повертає пустий об'єкт.

.Діаграма послідовності отримання інформації про майстер-версію регламенту
[plantuml]
----
include::partial$versions/get-master-version.puml[]
----

=== Отримання списку всіх версій-кандидатів регламенту

Повертає список всіх версій-кандидатів регламенту: їх ідентифікатори, назви та опис.

.Діаграма послідовності отримання списку всіх версій-кандидатів регламенту
[plantuml]
----
include::partial$versions/get-version-candidates.puml[]
----

=== Отримання інформації про версію-кандидат регламенту

Повертає інформацію про версію-кандидата за ідентифікатором.

.Діаграма послідовності отримання інформації про версію-кандидат регламенту
[plantuml]
----
include::partial$versions/get-version-candidate.puml[]
----