gerrit:
  url: http://localhost:8081
  user: user
  password: pass
  head-branch: head-branch
  repository: repository
  repository-directory: ${java.io.tmpdir}/testDirectory

spring:
  cloud:
    vault:
      enabled: false
  cache:
    cache-names: dates
    caffeine:
      spec: expireAfterAccess=5s

scheduled:
  dataModelSnapshotCron: '-'
  cleanRepositoriesCron: '-'
  repositoryRefreshCron: '-'

registry-regulation-management:
  async:
    enabled: false
  retry:
    enabled: false