gerrit:
  url: http://gerrit
  user: user
  password: pass
  head-branch: head-branch
  repository: repository

spring:
  cloud:
    vault:
      enabled: false
  cache:
    cache-names: dates
    caffeine:
      spec: expireAfterAccess=10s