apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-regulation-management-properties
data:
  config.yaml: |-
    server:
      max-http-header-size: 32KB
    {{- if eq .Values.deployProfile "dev" }}
    management.endpoints.web.exposure.include: '*'
    {{- else }}
    management.endpoints.web.exposure.include: 'health, prometheus'
    {{- end }}
    s3:
      config:
        client: {{ .Values.s3.config.client | toYaml | nindent 10 }}
        options: {{ .Values.s3.config.options | toYaml | nindent 10 }}

    user-import-ceph:
      http-endpoint: {{ .Values.userImportCeph.httpEndpoint }}
      bucketName: {{ .Values.userImportCeph.bucketName }}

    data:
      jobName: {{ .Values.data.jobName }}

    gerrit:
      url: {{ .Values.gerrit.url }}
      repository: {{ .Values.gerrit.repository }}
      headBranch: {{ .Values.gerrit.headBranch }}
      repositoryDirectory: {{ .Values.gerrit.repositoryDirectory }}

    scheduled:
      repositoryRefreshCron: {{ .Values.scheduled.repositoryRefreshCron }}
      repositoryRefreshTimezone: {{ .Values.scheduled.repositoryRefreshTimezone }}
      cleanRepositoriesCron: {{ .Values.scheduled.cleanRepositoriesCron }}
      cleanRepositoriesTimezone: {{ .Values.scheduled.cleanRepositoriesTimezone }}

    spring:
      cache:
        cache-names: {{.Values.cache.names}}
        caffeine:
          spec: {{.Values.cache.spec}}