apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.registryRegulationManagement.volume.claimName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.registryRegulationManagement.volume.size }}
  storageClassName: {{ .Values.global.storageClass }}
  volumeMode: Filesystem